# Artificial Neural Network

### Importing the libraries

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [2]:
tf.__version__

'2.2.0'

## Part 1 - Data Preprocessing

### Importing the dataset

In [18]:
dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values

In [19]:
X

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [20]:
y

array([1, 0, 1, ..., 1, 1, 0])

### Encoding categorical data

Label Encoding the "Gender" column

In [21]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:,2] = le.fit_transform(X[:,2])

In [22]:
X[:,2]

array([0, 0, 0, ..., 0, 1, 0], dtype=object)

One Hot Encoding the "Geography" column

In [23]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[1])],remainder='passthrough')
# You just have to change the index to which you want to one hot encode.
X = np.array(ct.fit_transform(X)) 

### Splitting the dataset into the Training set and Test set

In [24]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state = 0)

### Feature Scaling

In [25]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.fit_transform(X_test)

## Part 2 - Building the ANN

### Initializing the ANN

In [30]:
model = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [40]:
model.add(tf.keras.layers.Dense(units = 10,activation = 'relu'))

### Adding the second hidden layer

In [41]:
model.add(tf.keras.layers.Dense(units = 10,activation = 'relu'))

### Adding the output layer

In [42]:
model.add(tf.keras.layers.Dense(units =1,activation = 'sigmoid'))

## Part 3 - Training the ANN

### Compiling the ANN

In [43]:
model.compile(optimizer='adam',loss= 'binary_crossentropy',metrics=['accuracy'])

### Training the ANN on the Training set

In [44]:
model.fit(X_train,y_train,epochs = 80,batch_size = 32)

Epoch 1/80
250/250 [==============================] - 2s 8ms/step - loss: 0.5675 - accuracy: 0.7943
Epoch 2/80
250/250 [==============================] - 2s 9ms/step - loss: 0.4698 - accuracy: 0.7960
Epoch 3/80
250/250 [==============================] - 2s 7ms/step - loss: 0.4484 - accuracy: 0.7960
Epoch 4/80
250/250 [==============================] - 1s 6ms/step - loss: 0.4366 - accuracy: 0.8152
Epoch 5/80
250/250 [==============================] - 1s 6ms/step - loss: 0.4295 - accuracy: 0.8307
Epoch 6/80
250/250 [==============================] - 2s 6ms/step - loss: 0.4249 - accuracy: 0.8328
Epoch 7/80
250/250 [==============================] - 2s 7ms/step - loss: 0.4215 - accuracy: 0.8366
Epoch 8/80
250/250 [==============================] - 2s 6ms/step - loss: 0.4186 - accuracy: 0.8363
Epoch 9/80
250/250 [==============================] - 1s 6ms/step - loss: 0.4167 - accuracy: 0.8372
Epoch 10/80
250/250 [==============================] - 2s 7ms/step - loss: 0.4152 - accuracy: 0.8386

## Part 4 - Making the predictions and evaluating the model

### Predicting the result of a single observation

**Homework**

Use our ANN model to predict if the customer with the following informations will leave the bank: 

Geography: France

Credit Score: 600

Gender: Male

Age: 40 years old

Tenure: 3 years

Balance: \$ 60000

Number of Products: 2

Does this customer have a credit card ? Yes

Is this customer an Active Member: Yes

Estimated Salary: \$ 50000

So, should we say goodbye to that customer ?

**Solution**

In [50]:
sc.transform([[1,0,0,600,0,40,3,60000,2,1,1,50000]])

array([[ 1.04501206, -0.61433742, -0.57427105, -0.52978695, -1.11339196,
         0.07611425, -0.739106  , -0.29407315,  0.80136281,  0.66011376,
         0.97628121, -0.86697328]])

In [52]:
model.predict(sc.transform([[1,0,0,600,0,40,3,60000,2,1,1,50000]]))>0.5

array([[False]])

Therefore, our ANN model predicts that this customer stays in the bank!

**Important note 1:** Notice that the values of the features were all input in a double pair of square brackets. That's because the "predict" method always expects a 2D array as the format of its inputs. And putting our values into a double pair of square brackets makes the input exactly a 2D array.

**Important note 2:** Notice also that the "France" country was not input as a string in the last column but as "1, 0, 0" in the first three columns. That's because of course the predict method expects the one-hot-encoded values of the state, and as we see in the first row of the matrix of features X, "France" was encoded as "1, 0, 0". And be careful to include these values in the first three columns, because the dummy variables are always created in the first columns.

### Predicting the Test set results

In [55]:
y_pred = model.predict(X_test)

In [56]:
y_pred = (y_pred > 0.5)

In [60]:
y_pred

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])

In [62]:
y_test = (y_test>0.5)

In [63]:
y_pred

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])

In [64]:
y_test

array([False,  True, False, ..., False, False, False])

### Making the Confusion Matrix

In [65]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test,y_pred)

In [66]:
cm

array([[1549,   46],
       [ 278,  127]])

In [67]:
accuracy_score(y_test,y_pred)

0.838